version: '3.8'

services:
  # 1. База данных
  db:
    image: postgres:15
    restart: unless-stopped
    # Используем значения напрямую из файла .env для безопасности
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5477:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Брокер сообщений для Celery
  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    restart: unless-stopped

  # 3. Наш Django-сервер
  web:
    build: .
    command: >
      sh -c "python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    # Подключаем наш сейф с секретами
    env_file:
      - .env

  # 4. Воркер Celery (выполняет задачи)
  celery_worker:
    build: .
    command: celery -A config worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - web
    # === ИСПРАВЛЕНИЕ: Даем воркеру доступ к ключам ===
    env_file:
      - .env

  # 5. Планировщик Celery (запускает задачи по расписанию)
  celery_beat:
    build: .
    command: celery -A config beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - celery_worker
    env_file:
      - .env

volumes:
  postgres_data: