"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ==========================================
# 1. СТРОГИЕ НАСТРОЙКИ БЕЗОПАСНОСТИ (ИЗ .ENV)
# ==========================================

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured("Критическая ошибка: Переменная DJANGO_SECRET_KEY не задана в .env!")

# Ожидает строку 'True' из .env. Если ничего нет — будет безопасно False.
DEBUG = os.environ.get('DEBUG') == 'True'

# Ожидает хосты через запятую: localhost,127.0.0.1,твоя-vps.com
allowed_hosts_env = os.environ.get('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = allowed_hosts_env.split(',') if allowed_hosts_env else []


# ==========================================
# 2. ПРИЛОЖЕНИЯ И MIDDLEWARE
# ==========================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'tracker',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# ==========================================
# 3. БАЗА ДАННЫХ (БЕЗ ХАРДКОДА ПАРОЛЕЙ)
# ==========================================

db_password = os.environ.get('DB_PASSWORD')
if not db_password:
    raise ImproperlyConfigured("Критическая ошибка: Переменная DB_PASSWORD не задана в .env!")

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'tracker_db'),
        'USER': os.environ.get('DB_USER', 'tracker_user'),
        'PASSWORD': db_password,
        'HOST': os.environ.get('DB_HOST', 'db'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# ==========================================
# 4. ВАЛИДАЦИЯ ПАРОЛЕЙ И ИНТЕРНАЦИОНАЛИЗАЦИЯ
# ==========================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ==========================================
# 5. СТАТИКА
# ==========================================

STATIC_URL = 'static/'


# ==========================================
# 6. НАСТРОЙКИ CELERY И REDIS
# ==========================================

CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://127.0.0.1:6380/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://127.0.0.1:6380/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'fetch-crypto-prices-daily': {
        'task': 'tracker.tasks.fetch_daily_crypto_prices',
        'schedule': crontab(hour=0, minute=0),
    },
}