# Generated by Django 6.0.6 on 2026-06-13 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Тикер')),
                ('name', models.CharField(max_length=100, verbose_name='Повна назва')),
                ('asset_type', models.CharField(choices=[('CRYPTO', 'Криптовалюта'), ('FIAT', 'Фіатна валюта')], max_length=10, verbose_name='Тип активу')),
            ],
            options={
                'verbose_name': 'Актив',
                'verbose_name_plural': 'Активи',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Купівля'), ('SELL', 'Продаж')], max_length=4, verbose_name='Тип угоди')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='Кількість')),
                ('execution_price', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='Ціна за одиницю')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Час проведення угоди')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tracker.asset', verbose_name='Актив')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Транзакція',
                'verbose_name_plural': 'Транзакції',
            },
        ),
        migrations.CreateModel(
            name='AssetPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата котирування')),
                ('close_price', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='Ціна закриття')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='tracker.asset', verbose_name='Актив')),
            ],
            options={
                'verbose_name': 'Історія ціни',
                'verbose_name_plural': 'Історії цін',
                'indexes': [models.Index(fields=['date'], name='tracker_ass_date_4a59cb_idx')],
                'unique_together': {('asset', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PortfolioPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.DecimalField(decimal_places=8, default=0.0, max_digits=18, verbose_name='Загальна кількість')),
                ('average_buy_price', models.DecimalField(decimal_places=8, default=0.0, max_digits=18, verbose_name='Середня ціна купівлі')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='tracker.asset', verbose_name='Актив')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Позиція в портфелі',
                'verbose_name_plural': 'Позиції в портфелі',
                'unique_together': {('user', 'asset')},
            },
        ),
    ]
